### PR TITLE
fix(mat4): small mat4 bugs

### PR DESCRIPTION
**Pull request by Flecart**
This PR fixes some small bugs in the Mat4 functions:

1. The implementation of `createAngleAxis` is different from the GLM one found in https://github.com/g-truc/glm/blob/0.9.5/glm/gtc/matrix_transform.inl#L207-L229
2. Axis rotation implementation as https://github.com/g-truc/glm/blob/0.9.5/glm/gtc/matrix_transform.inl#L47

### CODE REVIEW

**Comment by MasterQ32** [comment]
This was an explicit decision to implement it with `direction` not `center`. You probably mean a function named `createdLookAt`, which would have a `center` position, but having a `center` is way less common than having a general `direction`

**Comment by Flecart** [comment]
> This was an explicit decision to implement it with `direction` not `center`. You probably mean a function named `createdLookAt`, which would have a `center` position, but having a `center` is way less common than having a general `direction`

You're right, i reverted that commit. 
The other ones should be correct i think,
I'm reimplementing the https://learnopengl.com/Getting-started/OpenGL tutorial in Zig, this is why i got into those errors...

You can check the [examples](https://github.com/Flecart/zigatari/tree/main/src/chapter-6) (mainly 6 is about these mini-bugs) to compare the old version and this branch

**Comment by MasterQ32** [comment]
Are you sure those changes are correct? It looks like you're flipping some axis and changing handedness?

The coordinate system of ZLM is the OpenGL coordinate system, which is:

X=right
Y=up
Z=backwards (outwards from the screen)

**Comment by Flecart** [comment]
> Are you sure those changes are correct? It looks like you're flipping some axis and changing handedness?
> 
> The coordinate system of ZLM is the OpenGL coordinate system, which is:
> 
> X=right Y=up Z=backwards (outwards from the screen)

They work with the examples you find [here](https://github.com/Flecart/zig-learnopengl) and I have checked it's now the same logic as `GLM` original implementation (with just `direction` and not `center` [here](https://github.com/g-truc/glm/blob/0.9.5/glm/gtc/matrix_transform.inl#L384-L410).

So yeah, if the coordinate system is the same as the OpenGL coordinate system it is correct.

**Comment by nhawke** [comment]
I came here to submit a fix for the `createAngleAxis()` bug mysel since I was seeing issues. When I used `createAngleAxis()` for creating a rotation transformation, the rotation was the wrong way. I wanted to rotate 90 degrees around the positive Z. This is supposed to do a counter-clockwise rotation, but I was getting clockwise rotations. I think the matrix was transposed by mistake.

The result of this change also matches the rotation matrix found [on Wikipedia](https://en.wikipedia.org/wiki/Rotation_matrix#Rotation_matrix_from_axis_and_angle).

If the other changes in this PR are contentious, could we split the angle-axis change into its own PR?

**Comment by MasterQ32** [comment]
Can you resolve the conflicts? Will merge then :)

**Comment by Flecart** [comment]
@MasterQ32  Done.

**Pull request merged**
